# Generated by Django 6.0.3 on 2026-04-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='weight',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='left_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='right_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
